export type FirmTier = 'Tier 1' | 'Tier 2' | 'Boutique' | 'International'

export interface FirmOffice {
  city: string
  address: string
}

export interface Firm {
  slug: string
  logoFile?: string | null
  name: string
  shortName: string
  tier: FirmTier
  email: string
  website: string
  offices: FirmOffice[]
  practiceAreas: string[]
  description: string
  foundedYear?: number
  openRoles: number
}

const STORAGE = 'https://ixocubhkygrnildbzluz.supabase.co/storage/v1/object/public/firm-logos/'

export function logoUrl(file?: string | null): string | null {
  if (!file) return null
  return STORAGE + file.replace(/ /g, '%20')
}

export const ALL_FIRMS: Firm[] = [
  {
    slug: 'acas-law',
    logoFile: 'ACAS.jpg',
    name: 'ACAS-Law',
    shortName: 'ACAS',
    tier: 'Tier 1',
    email: 'recruit@acas-law.com',
    website: 'https://acas-law.com',
    offices: [{ city: 'Lagos', address: 'Victoria Island, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Dispute Resolution'],
    description: 'A leading Nigerian commercial law firm with particular strength in energy, corporate transactions, and dispute resolution.',
    foundedYear: 2000,
    openRoles: 0,
  },
  {
    slug: 'aelex',
    logoFile: 'aelex.jpg',
    name: 'AELEX',
    shortName: 'AELEX',
    tier: 'Tier 1',
    email: 'info@aelex.com',
    website: 'https://aelex.com',
    offices: [
      { city: 'Lagos', address: 'St. Nicholas House, Catholic Mission Street, Lagos Island, Lagos' },
      { city: 'Abuja', address: 'Plot 1254, Nnadedi Close, Off T.Y. Danjuma Street, Asokoro, Abuja' },
      { city: 'Port Harcourt', address: 'Plot 3, Aba Road, GRA Phase II, Port Harcourt' },
    ],
    practiceAreas: ['Energy & Natural Resources', 'Dispute Resolution', 'Arbitration', 'Shipping & Maritime', 'Corporate & Commercial'],
    description: 'A leading full-service West African law firm with exceptional expertise in energy, dispute resolution, and maritime law.',
    foundedYear: 2004,
    openRoles: 4,
  },
  {
    slug: 'aina-blankson',
    logoFile: 'aina blankson.jpg',
    name: 'Aina Blankson LP',
    shortName: 'Aina Blankson',
    tier: 'Tier 2',
    email: 'info@ainablankson.com',
    website: 'https://ainablankson.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Shipping & Maritime', 'Corporate & Commercial', 'Energy & Natural Resources', 'Dispute Resolution'],
    description: 'A leading maritime and shipping law firm in Nigeria, with additional expertise in corporate, energy, and commercial law.',
    foundedYear: 1994,
    openRoles: 0,
  },
  {
    slug: 'ajumogobia-okeke',
    logoFile: 'ajumogbia.jpg',
    name: 'Ajumogobia & Okeke',
    shortName: 'A&O Nigeria',
    tier: 'Tier 2',
    email: 'careers@ajumogobia-okeke.com',
    website: 'https://ajumogobia-okeke.com',
    offices: [{ city: 'Lagos', address: 'Lekki Phase 1, Lagos' }],
    practiceAreas: ['Energy & Natural Resources', 'Corporate & Commercial', 'Dispute Resolution', 'Shipping & Maritime'],
    description: 'A boutique firm with deep expertise in energy, maritime, and natural resources law.',
    openRoles: 0,
  },
  {
    slug: 'aluko-oyebode',
    logoFile: 'aluko-oyebode.jpg',
    name: 'Aluko & Oyebode',
    shortName: 'Aluko & Oyebode',
    tier: 'Tier 1',
    email: 'careers@aluko-oyebode.com',
    website: 'https://aluko-oyebode.com',
    offices: [
      { city: 'Lagos', address: '1 Murtala Muhammed Drive, Ikoyi, Lagos' },
      { city: 'Abuja', address: 'Plot 2093, Ladoke Akintola Boulevard, Garki II, Abuja' },
      { city: 'Port Harcourt', address: '4 Igbodo Street, Old GRA, Port Harcourt' },
    ],
    practiceAreas: ['Banking & Finance', 'Capital Markets', 'Corporate & Commercial', 'Energy & Natural Resources', 'Dispute Resolution'],
    description: "Nigeria's largest law firm by headcount, offering a full range of corporate and commercial legal services with offices across the country.",
    foundedYear: 1993,
    openRoles: 4,
  },
  {
    slug: 'banwo-ighodalo',
    logoFile: 'banwo-ighodalo.jpg',
    name: 'Banwo & Ighodalo',
    shortName: 'Banwo & Ighodalo',
    tier: 'Tier 1',
    email: 'hr@banwo-ighodalo.com',
    website: 'https://banwo-ighodalo.com',
    offices: [{ city: 'Lagos', address: '98 Awolowo Road, Ikoyi, Lagos' }],
    practiceAreas: ['Capital Markets', 'Corporate & Commercial', 'Banking & Finance', 'Dispute Resolution', 'Tax'],
    description: 'A leading Nigerian law firm with particular strength in capital markets, banking and finance, and corporate transactions.',
    foundedYear: 1991,
    openRoles: 2,
  },
  {
    slug: 'blackfriars-law',
    logoFile: 'blackfriars-law.jpg',
    name: 'Blackfriars Law',
    shortName: 'Blackfriars',
    tier: 'Boutique',
    email: 'recruitment@blackfriars-law.com',
    website: 'https://blackfriars-law.com',
    offices: [{ city: 'Lagos', address: '28 McCarthy Street, Onikan, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Banking & Finance'],
    description: 'A boutique commercial law firm offering focused expertise in corporate transactions and dispute resolution.',
    foundedYear: 2008,
    openRoles: 0,
  },
  {
    slug: 'bloomfield-law',
    logoFile: 'bloomfield-law.ico',
    name: 'Bloomfield Law Practice',
    shortName: 'Bloomfield',
    tier: 'Tier 2',
    email: 'employment@bloomfield-law.com',
    website: 'https://bloomfield-law.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Intellectual Property', 'Dispute Resolution'],
    description: 'A commercial law firm offering expertise across corporate transactions, banking, intellectual property, and dispute resolution.',
    foundedYear: 2005,
    openRoles: 0,
  },
  {
    slug: 'dealhq-partners',
    logoFile: 'Deal Hq.jpg',
    name: 'DealHQ Partners',
    shortName: 'DealHQ',
    tier: 'Boutique',
    email: 'info@dealhqpartner.com',
    website: 'https://dealhqpartner.com',
    offices: [{ city: 'Lagos', address: '3B Dr. Omon Ebhomenye Street, Lekki Phase 1, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Capital Markets'],
    description: 'A transactions-focused boutique law firm specialising in corporate finance, capital markets, and commercial advisory.',
    foundedYear: 2015,
    openRoles: 0,
  },
  {
    slug: 'detail-solicitors',
    logoFile: 'Detail solicitors.jpg',
    name: 'Detail Solicitors',
    shortName: 'Detail',
    tier: 'Tier 1',
    email: 'nysc@detailsolicitors.com',
    website: 'https://detailsolicitors.com',
    offices: [{ city: 'Lagos', address: '235A Igbosere Road, Lagos Island, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Intellectual Property', 'Tax', 'Banking & Finance'],
    description: 'A specialist commercial firm with a formidable reputation in intellectual property, corporate advisory, and tax matters.',
    openRoles: 2,
  },
  {
    slug: 'famsville-solicitors',
    logoFile: 'Famsville.jpg',
    name: 'Famsville Solicitors',
    shortName: 'Famsville',
    tier: 'Boutique',
    email: 'info@famsvillesolicitors.com',
    website: 'https://famsvillesolicitors.com',
    offices: [{ city: 'Lagos', address: '28B Association Way, Dolphin Estate, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Banking & Finance'],
    description: 'A boutique commercial law firm providing focused legal services across corporate, finance, and dispute resolution.',
    foundedYear: 2012,
    openRoles: 0,
  },
  {
    slug: 'g-elias',
    logoFile: 'Elias.jpeg',
    name: 'G. Elias & Co',
    shortName: 'G. Elias',
    tier: 'Tier 1',
    email: 'info@gelias.com',
    website: 'https://gelias.com',
    offices: [{ city: 'Lagos', address: '4 Saka Tinubu Street, Victoria Island, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Telecommunications', 'Dispute Resolution', 'Tax', 'Capital Markets'],
    description: 'A renowned commercial law firm with a distinguished heritage and leading practice in telecommunications and corporate law.',
    foundedYear: 1944,
    openRoles: 1,
  },
  {
    slug: 'george-etomi',
    logoFile: 'george-etomi.jpg',
    name: 'George Etomi & Partners',
    shortName: 'George Etomi',
    tier: 'Tier 2',
    email: 'info@geplaw.com',
    website: 'https://geplaw.com',
    offices: [{ city: 'Lagos', address: '1b Tiramiyu Belo-Osagie Avenue, Parkview Estate, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Dispute Resolution', 'Banking & Finance'],
    description: 'A full-service commercial law firm with deep expertise in energy, corporate transactions, and dispute resolution.',
    foundedYear: 1994,
    openRoles: 0,
  },
  {
    slug: 'jackson-etti-edu',
    logoFile: 'Jackson etti.png',
    name: 'Jackson, Etti & Edu',
    shortName: 'JEE',
    tier: 'Tier 1',
    email: 'info@jee.com.ng',
    website: 'https://jee.com.ng',
    offices: [{ city: 'Lagos', address: '52 Raymond Njoku Street, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Employment', 'Intellectual Property', 'Real Estate'],
    description: 'A well-established firm with broad commercial expertise, particularly recognised for its employment law and intellectual property practice.',
    openRoles: 1,
  },
  {
    slug: 'kenna-partners',
    logoFile: 'kenna-partners.png',
    name: 'Kenna Partners',
    shortName: 'Kenna Partners',
    tier: 'Tier 1',
    email: 'careers@kennapartners.com',
    website: 'https://kennapartners.com',
    offices: [{ city: 'Lagos', address: '9 Omo-Osagie Street, Off Awolowo Road, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Tax', 'Banking & Finance', 'Real Estate', 'Employment'],
    description: 'A full-service commercial law firm with deep expertise in corporate transactions, tax advisory, and real estate.',
    openRoles: 1,
  },
  {
    slug: 'mike-igbokwe',
    logoFile: 'mike-igbokwe.jpg',
    name: 'Mike Igbokwe & Co',
    shortName: 'Mike Igbokwe',
    tier: 'Boutique',
    email: 'mike@mikeigbokwe.com',
    website: 'https://mikeigbokwe.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Arbitration', 'Dispute Resolution', 'Shipping & Maritime'],
    description: "A specialist dispute resolution and arbitration practice led by one of Nigeria's foremost arbitration practitioners.",
    foundedYear: 1995,
    openRoles: 0,
  },
  {
    slug: 'olajide-oyewole',
    logoFile: 'olajide oyewole.jpg',
    name: 'Olajide Oyewole LLP',
    shortName: 'Olajide Oyewole',
    tier: 'Tier 1',
    email: 'careers@olajide-oyewole.com',
    website: 'https://olajide-oyewole.com',
    offices: [{ city: 'Lagos', address: 'UBA House, 57 Marina, Lagos Island, Lagos' }],
    practiceAreas: ['Banking & Finance', 'Tax', 'Corporate & Commercial', 'Capital Markets', 'Real Estate'],
    description: 'A full-service commercial law firm known for innovative legal solutions in banking, finance, and tax advisory.',
    openRoles: 2,
  },
  {
    slug: 'olaniwun-ajayi',
    logoFile: 'olaniwun-ajayi.jpg',
    name: 'Olaniwun Ajayi LP',
    shortName: 'Olaniwun Ajayi',
    tier: 'Tier 1',
    email: 'recruitment@olaniwunajayi.net',
    website: 'https://olaniwunajayi.net',
    offices: [
      { city: 'Lagos', address: 'The Adunola, Banana Island, Ikoyi, Lagos' },
      { city: 'Abuja', address: 'Plot 1119, Cadastral Zone A00, Central Business District, Abuja' },
    ],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Tax', 'Capital Markets'],
    description: "One of Nigeria's foremost full-service commercial law firms, widely recognised for its leading corporate and energy practice.",
    foundedYear: 1978,
    openRoles: 3,
  },
  {
    slug: 'perchstone-graeys',
    logoFile: 'perchstone.jpg',
    name: 'Perchstone & Graeys LP',
    shortName: 'Perchstone & Graeys',
    tier: 'Tier 1',
    email: 'perchstone@perchstoneandgraeys.com',
    website: 'https://perchstoneandgraeys.com',
    offices: [{ city: 'Lagos', address: '4 Obalende Road, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Capital Markets', 'Dispute Resolution', 'Real Estate'],
    description: 'A full-service law firm providing comprehensive corporate and commercial legal services to domestic and international clients.',
    openRoles: 1,
  },
  {
    slug: 'primera-africa',
    logoFile: 'Primera.jpg',
    name: 'Primera Africa Legal',
    shortName: 'Primera Africa',
    tier: 'Tier 2',
    email: 'info@primeraal.com',
    website: 'https://primeraal.com',
    offices: [{ city: 'Lagos', address: '1B Utomi Aire Avenue, Off Fola Osibo, Lekki Phase 1, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Capital Markets', 'Energy & Natural Resources'],
    description: 'A leading commercial law firm with a strong focus on banking, finance, capital markets, and energy transactions.',
    foundedYear: 2008,
    openRoles: 0,
  },
  {
    slug: 'punuka',
    logoFile: 'punuka.png',
    name: 'Punuka Attorneys & Solicitors',
    shortName: 'Punuka',
    tier: 'Tier 2',
    email: 'careers@punuka.com',
    website: 'https://punuka.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Energy & Natural Resources', 'Tax'],
    description: 'A commercial law firm with strong expertise in corporate transactions, dispute resolution, and energy law.',
    foundedYear: 1993,
    openRoles: 0,
  },
  {
    slug: 'resolution-law',
    logoFile: 'resolution.jpg',
    name: 'Resolution Law Firm',
    shortName: 'Resolution Law',
    tier: 'Boutique',
    email: 'info@resolutionlawng.com',
    website: 'https://resolutionlawng.com',
    offices: [{ city: 'Lagos', address: '50/52 Toyin Street, Ikeja, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Intellectual Property'],
    description: 'A boutique commercial law firm offering expertise in corporate advisory, dispute resolution, and intellectual property.',
    foundedYear: 2010,
    openRoles: 0,
  },
  {
    slug: 'simmons-cooper',
    logoFile: 'simmons-cooper.png',
    name: 'Simmons Cooper Partners',
    shortName: 'Simmons Cooper',
    tier: 'Tier 2',
    email: 'careers@scp-law.com',
    website: 'https://scp-law.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Dispute Resolution'],
    description: 'A full-service commercial law firm with strong expertise in energy, corporate, and finance transactions.',
    foundedYear: 2003,
    openRoles: 0,
  },
  {
    slug: 'spa-ajibade',
    logoFile: 'SPA ajibade.jpg',
    name: 'SPA Ajibade & Co',
    shortName: 'SPA Ajibade',
    tier: 'Tier 1',
    email: 'hr@spaajibade.com',
    website: 'https://spaajibade.com',
    offices: [{ city: 'Lagos', address: 'Churchgate Towers, PC 30 Afribank Street, Victoria Island, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Dispute Resolution', 'Capital Markets'],
    description: "One of Nigeria's leading full-service commercial law firms, widely recognised for its energy, corporate and finance practice.",
    foundedYear: 1994,
    openRoles: 0,
  },
  {
    slug: 'stren-blan-partners',
    logoFile: 'StrenBlanPartners.png',
    name: 'Stren & Blan Partners',
    shortName: 'Stren & Blan',
    tier: 'Tier 2',
    email: 'Careers@strenandblan.com',
    website: 'https://strenandblan.com',
    offices: [
      { city: 'Lagos', address: '3 Theophilus Orji Street, Off Fola Osibo Road, Lekki Phase 1, Lagos' },
      { city: 'Abuja', address: 'House 22, 21 Road Kado Estate Phase 1, Abuja' },
      { city: 'Enugu', address: 'Plot 30 Republic Estate Independence Layout, Enugu' },
    ],
    practiceAreas: ['Arbitration', 'Banking & Finance', 'Capital Markets', 'Energy & Natural Resources', 'Intellectual Property', 'Shipping & Maritime', 'Real Estate', 'Tax', 'Employment'],
    description: 'A full-service commercial law firm with offices in Lagos, Abuja, and Enugu, offering broad expertise across transactions, disputes, and regulatory matters.',
    openRoles: 0,
  },
  {
    slug: 'streamsowers-kohn',
    logoFile: 'streamsowers.jpg',
    name: 'Streamsowers & Kohn',
    shortName: 'Streamsowers',
    tier: 'Tier 1',
    email: 'info@streamsowers.com',
    website: 'https://streamsowers.com',
    offices: [{ city: 'Lagos', address: '12 Adetokunbo Ademola Street, Victoria Island, Lagos' }],
    practiceAreas: ['Dispute Resolution', 'Arbitration', 'Corporate & Commercial', 'Banking & Finance'],
    description: "Nigeria's pre-eminent dispute resolution firm, with unrivalled expertise in commercial arbitration and litigation.",
    foundedYear: 1993,
    openRoles: 2,
  },
  {
    slug: 'tayo-oyetibo',
    logoFile: 'TayoOyetibo.jpg',
    name: 'Tayo Oyetibo LP',
    shortName: 'Tayo Oyetibo',
    tier: 'Tier 2',
    email: 'reception@tayooyetibolaw.com',
    website: 'https://tayooyetibolaw.com',
    offices: [{ city: 'Lagos', address: 'Plot 6, Block 113 Lekki-Epe Expressway, Lekki Phase 1, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Banking & Finance', 'Energy & Natural Resources'],
    description: 'A full-service commercial law firm with expertise in corporate transactions, energy, and dispute resolution.',
    foundedYear: 1996,
    openRoles: 0,
  },
  {
    slug: 'templars',
    logoFile: 'templars.jpg',
    name: 'Templars',
    shortName: 'Templars',
    tier: 'Tier 1',
    email: 'careers@templars-law.com',
    website: 'https://templars-law.com',
    offices: [
      { city: 'Lagos', address: '13A Idowu Taylor Street, Victoria Island, Lagos' },
      { city: 'Abuja', address: 'Plot 1412 Tigris Crescent, Maitama, Abuja' },
    ],
    practiceAreas: ['Energy & Natural Resources', 'Corporate & Commercial', 'Dispute Resolution', 'Capital Markets', 'Banking & Finance'],
    description: 'A top-tier commercial law firm known for its strong energy and corporate practice, serving multinationals and major Nigerian businesses.',
    foundedYear: 2009,
    openRoles: 3,
  },
  {
    slug: 'udo-udoma-bello-osagie',
    logoFile: 'udo-udoma.webp',
    name: 'Udo Udoma & Bello-Osagie',
    shortName: 'UUBO',
    tier: 'Tier 1',
    email: 'careers@uubo.org',
    website: 'https://uubo.org',
    offices: [
      { city: 'Lagos', address: '10 Amodu Ojikutu Street, Victoria Island, Lagos' },
      { city: 'Abuja', address: 'Plot 1400 Shehu Shagari Way, Maitama, Abuja' },
    ],
    practiceAreas: ['Corporate & Commercial', 'Capital Markets', 'Banking & Finance', 'Dispute Resolution', 'Tax'],
    description: "One of Nigeria's foremost law firms, offering exceptional legal services across corporate, finance, and dispute resolution practice areas.",
    foundedYear: 1996,
    openRoles: 2,
  },
  {
    slug: 'wole-olanipekun',
    logoFile: 'wole olanipekun.jpg',
    name: 'Wole Olanipekun & Co',
    shortName: 'Wole Olanipekun',
    tier: 'Tier 1',
    email: 'info@woleolanipekun.com',
    website: 'https://woleolanipekun.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Dispute Resolution', 'Corporate & Commercial', 'Public Law & Regulatory'],
    description: 'A distinguished Nigerian law firm with a strong reputation in litigation, arbitration, and corporate advisory.',
    foundedYear: 1988,
    openRoles: 0,
  },
]

export function getMonogram(name: string): string {
  return name
    .split(' ')
    .filter(w => w.length > 2 && !['and', 'LLP', 'LP', 'Co', 'the'].includes(w))
    .slice(0, 2)
    .map(w => w[0])
    .join('')
    .toUpperCase()
}

