export type OpportunityCategory = 
  | 'internship_law'
  | 'scholarship_local'
  | 'scholarship_international'
  | 'grad_trainee_banking'
  | 'grad_trainee_energy'
  | 'grad_trainee_fintech'
  | 'grad_trainee_other'

export type EligibilityLevel = 'undergraduate' | 'law_graduate' | 'experienced_lawyer'

export interface Opportunity {
  id: string
  title: string
  organisation: string
  category: OpportunityCategory
  eligibility: EligibilityLevel[]
  location: string
  isInternational: boolean
  deadline: string | null
  isRolling: boolean
  amount?: string
  duration?: string
  description: string
  applyUrl?: string
  applyEmail?: string
  isVerified: boolean
  isClosingSoon: boolean
  tags: string[]
}

export const ALL_OPPORTUNITIES: Opportunity[] = [
  // Law firm internships
  {
    id: 'olaniwun-law-intern-2025',
    title: 'Law Student Internship 2025',
    organisation: 'Olaniwun Ajayi LP',
    category: 'internship_law',
    eligibility: ['undergraduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-07-31',
    isRolling: false,
    duration: '4–6 weeks',
    description: 'Structured internship for penultimate and final-year law students. Rotate across corporate, energy, and tax practice groups.',
    applyEmail: 'recruitment@olaniwunajayi.net',
    isVerified: true,
    isClosingSoon: false,
    tags: ['law student', 'corporate', 'energy'],
  },
  {
    id: 'templars-vacation-2025',
    title: '2025 Vacation Scheme',
    organisation: 'Templars',
    category: 'internship_law',
    eligibility: ['undergraduate'],
    location: 'Lagos · Abuja',
    isInternational: false,
    deadline: '2025-06-15',
    isRolling: false,
    duration: '3 weeks',
    description: 'Templars flagship scheme for law students. Immersive exposure to energy, corporate, and dispute resolution matters. Stipend provided.',
    amount: 'Stipend provided',
    applyEmail: 'careers@templars-law.com',
    isVerified: true,
    isClosingSoon: true,
    tags: ['vacation scheme', 'energy', 'corporate'],
  },
  {
    id: 'aluko-intern-2025',
    title: 'Student Attachment Programme',
    organisation: 'Aluko & Oyebode',
    category: 'internship_law',
    eligibility: ['undergraduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: null,
    isRolling: true,
    duration: '4 weeks',
    description: 'Rolling placement programme for 300–500 level law students. Placements across banking, capital markets, and corporate teams.',
    applyEmail: 'careers@aluko-oyebode.com',
    isVerified: true,
    isClosingSoon: false,
    tags: ['law student', 'banking', 'capital markets'],
  },
  {
    id: 'aelex-intern-2025',
    title: 'Summer Internship — Law Students',
    organisation: 'AELEX',
    category: 'internship_law',
    eligibility: ['undergraduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-07-01',
    isRolling: false,
    duration: '6 weeks',
    description: 'Hands-on experience in energy, arbitration, and maritime law. Open to students in their penultimate or final year.',
    applyEmail: 'info@aelex.com',
    isVerified: true,
    isClosingSoon: false,
    tags: ['energy', 'arbitration', 'maritime'],
  },
  {
    id: 'streamsowers-arbitration-intern',
    title: 'Arbitration Intern',
    organisation: 'Streamsowers & Köhn',
    category: 'internship_law',
    eligibility: ['undergraduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-06-25',
    isRolling: false,
    duration: '4 weeks',
    description: 'Work alongside Nigeria\'s leading arbitration practice. Assist with research, pleadings, and case management.',
    applyEmail: 'info@streamsowers.com',
    isVerified: true,
    isClosingSoon: false,
    tags: ['arbitration', 'dispute resolution'],
  },

  // Local scholarships
  {
    id: 'nimasa-scholarship',
    title: 'NIMASA Maritime Law Scholarship',
    organisation: 'Nigerian Maritime Administration',
    category: 'scholarship_local',
    eligibility: ['undergraduate'],
    location: 'Nigeria',
    isInternational: false,
    deadline: '2025-08-30',
    isRolling: false,
    amount: 'Full tuition + stipend',
    description: 'Annual scholarship for law students with interest in maritime and shipping law. Includes placement at NIMASA legal department.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['maritime', 'shipping', 'government'],
  },
  {
    id: 'aluko-scholarship',
    title: 'Aluko & Oyebode Law Prize',
    organisation: 'Aluko & Oyebode',
    category: 'scholarship_local',
    eligibility: ['undergraduate'],
    location: 'Nigeria',
    isInternational: false,
    deadline: '2025-09-30',
    isRolling: false,
    amount: '₦500,000',
    description: 'Annual cash prize awarded to the top-ranked law student at a partner Nigerian university. Recipients receive an automatic internship offer.',
    applyEmail: 'careers@aluko-oyebode.com',
    isVerified: true,
    isClosingSoon: false,
    tags: ['prize', 'undergraduate'],
  },
  {
    id: 'cac-legal-bursary',
    title: 'Corporate Affairs Commission Bursary',
    organisation: 'Corporate Affairs Commission',
    category: 'scholarship_local',
    eligibility: ['undergraduate'],
    location: 'Nigeria',
    isInternational: false,
    deadline: '2025-07-15',
    isRolling: false,
    amount: '₦300,000 per annum',
    description: 'Merit-based bursary for 400-level law students interested in corporate law and company secretarial practice.',
    isVerified: false,
    isClosingSoon: false,
    tags: ['corporate law', 'government', 'bursary'],
  },

  // International scholarships
  {
    id: 'british-council-llm',
    title: 'Chevening Scholarship',
    organisation: 'UK Government / British Council',
    category: 'scholarship_international',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'United Kingdom',
    isInternational: true,
    deadline: '2025-11-04',
    isRolling: false,
    amount: 'Full LLM funding',
    description: 'Fully-funded one-year LLM scholarship for outstanding Nigerian lawyers with leadership potential. Covers tuition, living costs, and flights.',
    applyUrl: 'https://chevening.org',
    isVerified: true,
    isClosingSoon: false,
    tags: ['LLM', 'UK', 'fully funded', 'leadership'],
  },
  {
    id: 'commonwealth-scholarship',
    title: 'Commonwealth Shared Scholarship',
    organisation: 'Commonwealth Scholarship Commission',
    category: 'scholarship_international',
    eligibility: ['law_graduate'],
    location: 'United Kingdom',
    isInternational: true,
    deadline: '2025-12-15',
    isRolling: false,
    amount: 'Full postgraduate funding',
    description: 'Fully-funded scholarship for postgraduate study in the UK. Open to graduates from Commonwealth nations including Nigeria.',
    applyUrl: 'https://cscuk.fcdo.gov.uk',
    isVerified: true,
    isClosingSoon: false,
    tags: ['postgraduate', 'UK', 'fully funded'],
  },
  {
    id: 'fordham-llm-award',
    title: 'Fordham International Law Scholarship',
    organisation: 'Fordham University School of Law',
    category: 'scholarship_international',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'New York, USA',
    isInternational: true,
    deadline: '2026-02-01',
    isRolling: false,
    amount: 'Partial tuition waiver',
    description: 'Merit scholarship for international students pursuing an LLM at Fordham Law, New York. Strong preference for candidates with commercial law backgrounds.',
    applyUrl: 'https://law.fordham.edu',
    isVerified: true,
    isClosingSoon: false,
    tags: ['LLM', 'USA', 'commercial law'],
  },
  {
    id: 'leiden-advanced-llm',
    title: 'Leiden Advanced LLM in International Law',
    organisation: 'Leiden Law School',
    category: 'scholarship_international',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'Netherlands',
    isInternational: true,
    deadline: '2026-01-15',
    isRolling: false,
    amount: 'Partial scholarship available',
    description: 'Advanced LLM programme at one of Europe\'s oldest universities. Specialisations in international business law, public international law, and trade law.',
    applyUrl: 'https://leidenuniv.nl',
    isVerified: true,
    isClosingSoon: false,
    tags: ['LLM', 'Netherlands', 'international law'],
  },

  // Graduate trainee — Banking
  {
    id: 'access-bank-grad-trainee',
    title: 'Legal Graduate Trainee Programme',
    organisation: 'Access Bank Plc',
    category: 'grad_trainee_banking',
    eligibility: ['law_graduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-07-31',
    isRolling: false,
    duration: '12 months',
    description: 'Structured programme for fresh law graduates joining Access Bank\'s legal and compliance function. Rotations across credit, retail, and corporate banking legal teams.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['banking', 'compliance', 'corporate'],
  },
  {
    id: 'zenith-bank-legal-trainee',
    title: 'Legal Trainee — Compliance & Regulatory',
    organisation: 'Zenith Bank Plc',
    category: 'grad_trainee_banking',
    eligibility: ['law_graduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: null,
    isRolling: true,
    duration: '18 months',
    description: 'Ongoing recruitment of law graduates into Zenith\'s Group Legal and Compliance division. Ideal for candidates interested in financial regulation and banking law.',
    isVerified: false,
    isClosingSoon: false,
    tags: ['banking', 'regulatory', 'compliance'],
  },
  {
    id: 'stanbic-ibtc-legal',
    title: 'Legal & Compliance Graduate',
    organisation: 'Stanbic IBTC Bank',
    category: 'grad_trainee_banking',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'Lagos · Abuja',
    isInternational: false,
    deadline: '2025-08-15',
    isRolling: false,
    duration: '12 months',
    description: 'Graduate role within Standard Bank Group\'s Nigerian legal team. Exposure to cross-border transactions, regulatory matters, and internal litigation.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['banking', 'compliance', 'cross-border'],
  },

  // Graduate trainee — Energy
  {
    id: 'seplat-legal-grad',
    title: 'Legal Affairs Graduate Trainee',
    organisation: 'Seplat Energy Plc',
    category: 'grad_trainee_energy',
    eligibility: ['law_graduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-07-20',
    isRolling: false,
    duration: '12 months',
    description: 'Graduate trainee role within Seplat\'s in-house legal team. Work on oil and gas contracts, regulatory filings, and joint venture agreements.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['energy', 'oil & gas', 'contracts'],
  },
  {
    id: 'total-energies-legal',
    title: 'In-House Legal Trainee',
    organisation: 'TotalEnergies Nigeria',
    category: 'grad_trainee_energy',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-09-01',
    isRolling: false,
    duration: '24 months',
    description: 'Competitive graduate programme for lawyers joining TotalEnergies\' Nigerian legal department. Exposure to upstream, downstream, and LNG matters.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['energy', 'LNG', 'upstream', 'downstream'],
  },

  // Graduate trainee — Fintech
  {
    id: 'flutterwave-legal-trainee',
    title: 'Legal & Regulatory Graduate',
    organisation: 'Flutterwave',
    category: 'grad_trainee_fintech',
    eligibility: ['law_graduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: null,
    isRolling: true,
    description: 'Join Flutterwave\'s fast-growing legal and compliance team. Work on licensing, data privacy, cross-border payment regulations, and commercial contracts.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['fintech', 'data privacy', 'payments', 'licensing'],
  },
  {
    id: 'paystack-legal',
    title: 'Legal Counsel (Junior)',
    organisation: 'Paystack',
    category: 'grad_trainee_fintech',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-08-01',
    isRolling: false,
    description: 'Paystack is looking for a junior lawyer to join its growing legal function. You\'ll handle commercial agreements, CBN compliance, and product counselling.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['fintech', 'CBN', 'compliance', 'commercial'],
  },
  {
    id: 'moniepoint-legal-grad',
    title: 'Legal Graduate Programme',
    organisation: 'Moniepoint Inc.',
    category: 'grad_trainee_fintech',
    eligibility: ['law_graduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: null,
    isRolling: true,
    description: 'Rolling recruitment for lawyers joining Moniepoint\'s legal, compliance, and regulatory affairs team. Strong focus on payments regulation and financial inclusion policy.',
    isVerified: false,
    isClosingSoon: false,
    tags: ['fintech', 'payments', 'regulatory'],
  },

  // Graduate trainee — Other
  {
    id: 'dangote-legal-grad',
    title: 'Legal Trainee — Group Legal',
    organisation: 'Dangote Industries',
    category: 'grad_trainee_other',
    eligibility: ['law_graduate'],
    location: 'Lagos',
    isInternational: false,
    deadline: '2025-08-31',
    isRolling: false,
    duration: '18 months',
    description: 'Graduate placement within the Dangote Group legal function. Exposure to infrastructure contracts, regulatory affairs, employment law, and dispute management.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['conglomerate', 'infrastructure', 'employment'],
  },
  {
    id: 'mtn-legal-associate',
    title: 'Legal & Regulatory Associate',
    organisation: 'MTN Nigeria',
    category: 'grad_trainee_other',
    eligibility: ['law_graduate', 'experienced_lawyer'],
    location: 'Lagos',
    isInternational: false,
    deadline: null,
    isRolling: true,
    description: 'Role within MTN\'s legal, regulatory, and compliance division. Work on telecoms licensing, consumer protection matters, and commercial agreements.',
    isVerified: true,
    isClosingSoon: false,
    tags: ['telecoms', 'regulatory', 'licensing'],
  },
]

export const CATEGORY_META = {
  internship_law: {
    label: 'Law Firm Internships',
    description: 'Structured placements at leading Nigerian law firms — for law undergraduates.',
    eligibility: 'Law undergraduates (300–500 level)',
    icon: 'building',
  },
  scholarship_local: {
    label: 'Local Scholarships',
    description: 'Nigerian-based funding, prizes, and bursaries for law students and graduates.',
    eligibility: 'Nigerian undergraduates and graduates',
    icon: 'award',
  },
  scholarship_international: {
    label: 'International Scholarships',
    description: 'LLM funding, postgraduate awards, and fellowships from overseas institutions.',
    eligibility: 'Law graduates and experienced lawyers',
    icon: 'globe',
  },
  grad_trainee_banking: {
    label: 'Banking & Finance',
    description: 'Graduate roles within banks\' legal, compliance, and regulatory teams.',
    eligibility: 'Fresh law graduates and junior lawyers',
    icon: 'landmark',
  },
  grad_trainee_energy: {
    label: 'Oil, Gas & Energy',
    description: 'In-house legal roles at energy companies and multinationals.',
    eligibility: 'Fresh law graduates and experienced lawyers',
    icon: 'zap',
  },
  grad_trainee_fintech: {
    label: 'Fintech & Tech',
    description: 'Legal and regulatory roles at Nigeria\'s fastest-growing tech companies.',
    eligibility: 'Fresh law graduates and junior lawyers',
    icon: 'cpu',
  },
  grad_trainee_other: {
    label: 'Other Industries',
    description: 'Legal roles at conglomerates, telecoms, and other major corporations.',
    eligibility: 'Fresh law graduates and junior lawyers',
    icon: 'briefcase',
  },
}

