const fs = require('fs');
let data = fs.readFileSync('src/lib/firms-data.ts', 'utf8');

// Remove STL Attorneys block
const stlStart = data.indexOf("  {\n    slug: 'stl-attorneys'");
const stlEnd = data.indexOf('  },\n', stlStart) + 5;
if (stlStart > -1) {
  data = data.slice(0, stlStart) + data.slice(stlEnd);
  console.log('STL removed');
}

// New firms to add
const newFirms = `
  {
    slug: 'spa-ajibade',
    name: 'SPA Ajibade & Co',
    shortName: 'SPA Ajibade',
    tier: 'Tier 1',
    email: 'hr@spaajibade.com',
    website: 'https://spaajibade.com',
    offices: [{ city: 'Lagos', address: 'Churchgate Towers, PC 30 Afribank Street, Victoria Island, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Dispute Resolution', 'Capital Markets'],
    description: 'One of Nigeria\'s leading full-service commercial law firms, widely recognised for its energy, corporate and finance practice.',
    foundedYear: 1994,
    openRoles: 0,
  },
  {
    slug: 'acas-law',
    name: 'ACAS-Law',
    shortName: 'ACAS',
    tier: 'Tier 1',
    email: 'recruit@acas-law.com',
    website: 'https://acas-law.com',
    offices: [{ city: 'Lagos', address: 'Victoria Island, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Dispute Resolution'],
    description: 'A leading Nigerian commercial law firm with particular strength in energy, corporate transactions, and dispute resolution.',
    foundedYear: 2000,
    openRoles: 0,
  },
  {
    slug: 'wole-olanipekun',
    name: 'Wole Olanipekun & Co',
    shortName: 'Wole Olanipekun',
    tier: 'Tier 1',
    email: 'info@woleolanipekun.com',
    website: 'https://woleolanipekun.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Dispute Resolution', 'Corporate & Commercial', 'Public Law & Regulatory'],
    description: 'A distinguished Nigerian law firm with a strong reputation in litigation, arbitration, and corporate advisory.',
    foundedYear: 1988,
    openRoles: 0,
  },
  {
    slug: 'bloomfield-law',
    name: 'Bloomfield Law Practice',
    shortName: 'Bloomfield',
    tier: 'Tier 2',
    email: 'employment@bloomfield-law.com',
    website: 'https://bloomfield-law.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Intellectual Property', 'Dispute Resolution'],
    description: 'A commercial law firm offering expertise across corporate transactions, banking, intellectual property, and dispute resolution.',
    foundedYear: 2005,
    openRoles: 0,
  },
  {
    slug: 'simmons-cooper',
    name: 'Simmons Cooper Partners',
    shortName: 'Simmons Cooper',
    tier: 'Tier 2',
    email: 'careers@scp-law.com',
    website: 'https://scp-law.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Banking & Finance', 'Dispute Resolution'],
    description: 'A full-service commercial law firm with strong expertise in energy, corporate, and finance transactions.',
    foundedYear: 2003,
    openRoles: 0,
  },
  {
    slug: 'aina-blankson',
    name: 'Aina Blankson LP',
    shortName: 'Aina Blankson',
    logoFile: 'aina blankson.jpg',
    tier: 'Tier 2',
    email: 'info@ainablankson.com',
    website: 'https://ainablankson.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Shipping & Maritime', 'Corporate & Commercial', 'Energy & Natural Resources', 'Dispute Resolution'],
    description: 'A leading maritime and shipping law firm in Nigeria, with additional expertise in corporate, energy, and commercial law.',
    foundedYear: 1994,
    openRoles: 0,
  },
  {
    slug: 'punuka',
    name: 'Punuka Attorneys & Solicitors',
    shortName: 'Punuka',
    logoFile: 'punuka.png',
    tier: 'Tier 2',
    email: 'careers@punuka.com',
    website: 'https://punuka.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Energy & Natural Resources', 'Tax'],
    description: 'A commercial law firm with strong expertise in corporate transactions, dispute resolution, and energy law.',
    foundedYear: 1993,
    openRoles: 0,
  },
  {
    slug: 'mike-igbokwe',
    name: 'Mike Igbokwe & Co',
    shortName: 'Mike Igbokwe',
    tier: 'Boutique',
    email: 'mike@mikeigbokwe.com',
    website: 'https://mikeigbokwe.com',
    offices: [{ city: 'Lagos', address: 'Lagos, Nigeria' }],
    practiceAreas: ['Arbitration', 'Dispute Resolution', 'Shipping & Maritime'],
    description: 'A specialist dispute resolution and arbitration practice led by one of Nigeria\'s foremost arbitration practitioners.',
    foundedYear: 1995,
    openRoles: 0,
  },
  {
    slug: 'blackfriars-law',
    name: 'Blackfriars Law',
    shortName: 'Blackfriars',
    tier: 'Boutique',
    email: 'recruitment@blackfriars-law.com',
    website: 'https://blackfriars-law.com',
    offices: [{ city: 'Lagos', address: '28 McCarthy Street, Onikan, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Banking & Finance'],
    description: 'A boutique commercial law firm offering focused expertise in corporate transactions and dispute resolution.',
    foundedYear: 2008,
    openRoles: 0,
  },
  {
    slug: 'george-etomi',
    name: 'George Etomi & Partners',
    shortName: 'George Etomi',
    tier: 'Tier 2',
    email: 'info@geplaw.com',
    website: 'https://geplaw.com',
    offices: [{ city: 'Lagos', address: '1b Tiramiyu Belo-Osagie Avenue, Parkview Estate, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Energy & Natural Resources', 'Dispute Resolution', 'Banking & Finance'],
    description: 'A full-service commercial law firm with deep expertise in energy, corporate transactions, and dispute resolution.',
    foundedYear: 1994,
    openRoles: 0,
  },
  {
    slug: 'resolution-law',
    name: 'Resolution Law Firm',
    shortName: 'Resolution Law',
    tier: 'Boutique',
    email: 'info@resolutionlawng.com',
    website: 'https://resolutionlawng.com',
    offices: [{ city: 'Lagos', address: '50/52 Toyin Street, Ikeja, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Intellectual Property'],
    description: 'A boutique commercial law firm offering expertise in corporate advisory, dispute resolution, and intellectual property.',
    foundedYear: 2010,
    openRoles: 0,
  },
  {
    slug: 'dealhq-partners',
    name: 'DealHQ Partners',
    shortName: 'DealHQ',
    tier: 'Boutique',
    email: 'info@dealhqpartner.com',
    website: 'https://dealhqpartner.com',
    offices: [{ city: 'Lagos', address: '3B Dr. Omon Ebhomenye Street, Lekki Phase 1, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Capital Markets'],
    description: 'A transactions-focused boutique law firm specialising in corporate finance, capital markets, and commercial advisory.',
    foundedYear: 2015,
    openRoles: 0,
  },
  {
    slug: 'primera-africa',
    name: 'Primera Africa Legal',
    shortName: 'Primera Africa',
    tier: 'Tier 2',
    email: 'info@primeraal.com',
    website: 'https://primeraal.com',
    offices: [{ city: 'Lagos', address: '1B Utomi Aire Avenue, Off Fola Osibo, Lekki Phase 1, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Banking & Finance', 'Capital Markets', 'Energy & Natural Resources'],
    description: 'A leading commercial law firm with a strong focus on banking, finance, capital markets, and energy transactions.',
    foundedYear: 2008,
    openRoles: 0,
  },
  {
    slug: 'famsville-solicitors',
    name: 'Famsville Solicitors',
    shortName: 'Famsville',
    tier: 'Boutique',
    email: 'info@famsvillesolicitors.com',
    website: 'https://famsvillesolicitors.com',
    offices: [{ city: 'Lagos', address: '28B Association Way, Dolphin Estate, Ikoyi, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Banking & Finance'],
    description: 'A boutique commercial law firm providing focused legal services across corporate, finance, and dispute resolution.',
    foundedYear: 2012,
    openRoles: 0,
  },
  {
    slug: 'tayo-oyetibo',
    name: 'Tayo Oyetibo LP',
    shortName: 'Tayo Oyetibo',
    tier: 'Tier 2',
    email: 'reception@tayooyetibolaw.com',
    website: 'https://tayooyetibolaw.com',
    offices: [{ city: 'Lagos', address: 'Plot 6, Block 113 Lekki-Epe Expressway, Lekki Phase 1, Lagos' }],
    practiceAreas: ['Corporate & Commercial', 'Dispute Resolution', 'Banking & Finance', 'Energy & Natural Resources'],
    description: 'A full-service commercial law firm with expertise in corporate transactions, energy, and dispute resolution.',
    foundedYear: 1996,
    openRoles: 0,
  },
`;

// Insert before the closing bracket of ALL_FIRMS array
data = data.replace(']\n\nexport function getMonogram', newFirms + ']\n\nexport function getMonogram');

fs.writeFileSync('src/lib/firms-data.ts', data);
console.log('done - firms added');