import Link from 'next/link'
import type { Metadata } from 'next'
import TrackOnApply from '@/components/features/TrackOnApply'
import { notFound } from 'next/navigation'
import Footer from '@/components/layout/Footer'
import { ALL_FIRMS, firmLogo, getMonogram, isIndexable, isPubliclyReadable, type Firm } from '@/lib/firms-data'
import LogoFrame from '@/components/ui/LogoFrame'
import RankingBadges from '@/components/ui/RankingBadges'
import JsonLd, { SITE_URL, breadcrumb, openGraph } from '@/components/seo/JsonLd'
import { createClient } from '@/lib/supabase/server'

/* ⚠ THERE IS NO generateStaticParams HERE, AND IT MUST NOT BE ADDED BACK.
 *
 * Prerendering the twenty one Tier 1 slugs looks free: they never read a
 * cookie, so they could be flat HTML. It was tried and it broke every OTHER
 * profile in production. With generateStaticParams present, Next's default for
 * a param outside the list is to render it statically on demand and cache it,
 * and a static render cannot read cookies. Every gated profile answered 500
 * with digest DYNAMIC_SERVER_USAGE.
 *
 * `await connection()` does not rescue it either. It signals that a render
 * needs a request, but the render Next has already committed to here is a
 * prerender, so the signal is an error rather than a switch.
 *
 * The route is therefore dynamic for everybody. That is a real cost paid for
 * correctness, and a small one: these pages are server rendered per request
 * rather than served from cache, which Google indexes exactly the same way.
 * Getting both would mean Partial Prerendering, or serving gated addresses
 * from an authenticated route instead of the page. Either is a bigger change
 * than a fast TTFB on twenty one pages is worth today.
 */

/**
 * Per-firm metadata, which this page never had.
 *
 * Every profile shared the site-wide title, so fifty-nine pages went out
 * announcing themselves as "Esquirely | Nigeria's Legal Career Platform". A
 * search result for a firm's name has to say the firm's name, and a link
 * pasted into WhatsApp has to preview as that firm rather than as the site.
 *
 * EVERY PROFILE IS NOW INDEXED, gated ones included. See isIndexable for the
 * argument. What that changes here is the description, and the change matters
 * more than the robots line does: for a gated firm this string is now the
 * snippet under a live search result, and it used to end "Sign in to see the
 * full record." A snippet that describes the page's paywall rather than the
 * firm is the one thing that would make indexing these pages a mistake. Both
 * branches now describe the firm; they differ only in whether they promise the
 * application address, which is the one thing a gated page cannot deliver.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const firm = ALL_FIRMS.find(f => f.slug === slug)
  if (!firm) return { title: 'Firm not found' }

  const cities = firm.offices.map(o => o.city)
  const where = [...new Set(cities)].join(', ')
  const open = isPubliclyReadable(firm)

  return {
    title: firm.name,
    description: open
      ? `${firm.name}: offices, practice areas and how to apply. ${firm.description}`.slice(0, 300)
      : `${firm.name}: ${where ? `offices in ${where}, ` : ''}practice areas and independent rankings. ${firm.description}`.slice(0, 300),
    alternates: { canonical: `/firms/${firm.slug}` },
    /* Points at this route's OWN card, generated by the sibling
       opengraph-image.tsx, not the site default. That file is what makes a
       profile pasted into a group chat preview as the firm rather than as
       Esquirely, which is the whole reason the per-firm card exists. */
    openGraph: openGraph({
      path: `/firms/${firm.slug}`,
      title: `${firm.name} | Esquirely`,
      description: firm.description,
      image: `/firms/${firm.slug}/opengraph-image`,
      type: 'profile',
    }),
    ...(isIndexable(firm) ? {} : { robots: { index: false, follow: true } }),
  }
}

/** Firm mark for the profile header.
 *
 *  This carried its own copy of the storage URL and keyed off `logoFile`
 *  directly, which broke in two ways. Firms whose art was pulled from their own
 *  site have a null `logoFile` and so rendered nothing at all here, even with a
 *  perfectly good PNG in /public. And every other firm was served the untrimmed
 *  bucket original rather than the trimmed art the rest of the site uses, so
 *  this page sized its logos unlike the directory and the ticker.
 *
 *  Going through firmLogo() and LogoFrame fixes both, and means the three
 *  surfaces stay in step from here. */
function FirmAvatar({ firm }: { firm: Firm }) {
  const url = firmLogo(firm)

  if (!url) {
    /* Matches the directory's quiet placeholder rather than a solid ink block.
     * At this size the filled version was the heaviest thing on the page,
     * outweighing the firm's own name beside it. */
    return (
      <span className="firm-monogram firm-monogram-lg">
        <span className="grotesk-bold">{getMonogram(firm.name)}</span>
      </span>
    )
  }

  return <LogoFrame src={url} alt={firm.name} capHeight={3} maxWidth={9} plate />
}

/* Solid, matching the directory card this page is reached from. Same pin, one
   size up. A firm's offices are the one thing shown in both places, so the mark
   beside them should not change between the card and the profile.

   The geometry, and why it is what it is, is documented once beside the pair in
   src/app/firms/page.tsx. If that drawing changes, change this one in the same
   commit: two pins that disagree is worse than either pin. */
const MapPinIcon = () => (
  <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.53 13.02A6.5 6.5 0 1 1 17.47 13.02L12 21.8Z M12 6.6a2.9 2.9 0 1 0 0 5.8 2.9 2.9 0 0 0 0-5.8Z"
    />
  </svg>
)
const GlobeIcon = () => (<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>)
const MailIcon = () => (<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>)
const ArrowLeftIcon = () => (<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 19-7-7 7-7M19 12H5"/></svg>)

// Next 16 made `params` a Promise. Reading params.slug directly gave undefined,
// so every firm profile fell through to notFound().
/**
 * The firm, stated for machines.
 *
 * `LegalService` rather than plain `Organization`, because it is the specific
 * type and specificity is the whole point of doing this: it tells a consumer
 * that this page is about a law firm without needing to read a word of the prose.
 *
 * WHY THIS PAGE IS THE ONE WORTH MARKING UP FIRST. A profile here is the only
 * page on the open web that states a Nigerian firm's tier, its practice areas,
 * its offices and its Chambers, IFLR1000 and Legal 500 standing in one place.
 * That combination is what makes it citable when somebody asks an assistant
 * about the firm, and none of it is legible while it is only prose.
 *
 * ⚠ THE GATED FIELDS ARE OMITTED WHEN THE PAGE IS LOCKED, and `locked` is
 * passed in rather than recomputed so the schema and the page cannot disagree.
 * Emitting a street address in JSON-LD that the visible page withholds is not a
 * clever way to get the data indexed; it is the mismatch Google issues manual
 * actions for, and it would also hand out the exact field the gate exists to
 * protect. A locked profile still gets a name, a tier, cities and practice
 * areas, because all of those are on the page.
 */
function firmSchema(firm: Firm, locked: boolean) {
  const cities = [...new Set(firm.offices.map(o => o.city))]

  return {
    '@context': 'https://schema.org',
    '@type': 'LegalService',
    '@id': `${SITE_URL}/firms/${firm.slug}#firm`,
    name: firm.name,
    url: `${SITE_URL}/firms/${firm.slug}`,
    description: firm.description,
    ...(firm.website ? { sameAs: [firm.website] } : {}),
    ...(firm.foundedYear ? { foundingDate: String(firm.foundedYear) } : {}),
    areaServed: { '@type': 'Country', name: 'Nigeria' },
    knowsAbout: firm.practiceAreas,
    /* Cities are public on a locked page; street addresses and the careers
       address are not. `PostalAddress` without `streetAddress` is valid and
       says exactly as much as the page does. */
    address: firm.offices.map(o => ({
      '@type': 'PostalAddress',
      ...(locked ? {} : { streetAddress: o.address }),
      addressLocality: o.city,
      addressCountry: 'NG',
    })),
    ...(locked || !firm.email ? {} : { email: firm.email }),
    /* The page that lists it, so a consumer holding only this block can find
       its way back to the directory it came from. */
    isPartOf: { '@id': `${SITE_URL}/firms#page` },
    ...(cities.length ? { location: cities.join(', ') } : {}),
  }
}

export default async function FirmDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const firm = ALL_FIRMS.find(f => f.slug === slug)
  if (!firm) return notFound()

  /* Tier 1 profiles are open to everyone, including crawlers, and the rest ask
   * for an account. See isPubliclyReadable for why the line is drawn there.
   *
   * The session is still only read for a gated firm. It no longer buys static
   * rendering (see the note above generateMetadata), but it does mean a Tier 1
   * page serves without waiting on an auth round trip, which is the part of
   * that saving actually worth keeping. */
  let locked = false
  if (!isPubliclyReadable(firm)) {
    locked = !(await createClient().auth.getUser()).data.user
  }

  /* Firms a reader of this page would plausibly want next: same tier, and at
   * least one practice area in common. Ranked by how much practice overlap
   * there is, so the suggestions are about the work rather than the alphabet.
   * Falls back to tier alone for firms whose practice list is unusual, which
   * keeps the row populated instead of collapsing on the narrow cases. */
  const related = (() => {
    const overlap = (f: Firm) =>
      f.practiceAreas.filter(p => firm.practiceAreas.includes(p)).length

    const pool = ALL_FIRMS.filter(f => f.slug !== firm.slug)
    const scored = pool
      .map(f => ({ f, score: overlap(f) + (f.tier === firm.tier ? 1.5 : 0) }))
      .filter(x => x.score > 1.5)
      .sort((a, b) => b.score - a.score)

    // Six are rendered and CSS hides the last two below 1080px, because this is
    // a server component: there is no viewport to branch on at render time, and
    // shipping six costs two extra list items rather than a client boundary.
    const picked = scored.slice(0, 6).map(x => x.f)
    if (picked.length >= 3) return picked
    // Top up from the same tier so the row never renders half empty.
    const filler = pool.filter(f => f.tier === firm.tier && !picked.includes(f))
    return [...picked, ...filler].slice(0, 6)
  })()

  return (
    <>
      <JsonLd data={[firmSchema(firm, locked), breadcrumb([
        { name: 'Home', path: '/' },
        { name: 'Firms', path: '/firms' },
        { name: firm.name, path: `/firms/${firm.slug}` },
      ])]} />
      {/* No min-height. It was 100vh, which on a firm with one office and no
          open roles left a full screen of empty cream between the last line of
          content and the footer. The page is as long as it has things to say. */}
      <main style={{ backgroundColor: '#FAF6F0', paddingTop: '64px' }}>

        {/* Breadcrumb */}
        <div className="firm-profile-crumb">
          <div style={{ maxWidth: 'min(2200px, 94vw)', margin: '0 auto' }}>
            <Link href="/firms" className="back-link">
              <ArrowLeftIcon /> Firms directory
            </Link>
          </div>
        </div>

        {/* Header. The name leads. It previously sat below a row of three
            uppercase micro-labels, one of which was a green "Verified" chip
            shown on every firm in the directory and so meaningless as a
            distinction. Tier and founding year survive as a quiet meta line
            under the name, where they belong: they qualify the firm, they are
            not the headline. */}
        <div className="firm-profile-header">
          <div className="shell">
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '2rem', flexWrap: 'wrap' }}>
              <div style={{ paddingTop: '6px' }}><FirmAvatar firm={firm} /></div>
              <div>
                <h1 className="display-black firm-profile-name">
                  {firm.name}
                </h1>
                <div className="firm-profile-meta">
                  <span>{firm.tier}</span>
                  {firm.foundedYear && (
                    <>
                      <span className="firm-profile-dot" />
                      <span>Established {firm.foundedYear}</span>
                    </>
                  )}
                  <span className="firm-profile-dot" />
                  <span>{firm.offices.length === 1 ? '1 office' : `${firm.offices.length} offices`}</span>
                </div>
                <p className="grotesk-regular firm-profile-desc">
                  {firm.description}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Body.
            The grid lives in CSS, not in a style attribute. As an inline
            `1fr min(300px, 32%)` it could not be reached by a media query, so
            it stayed two columns all the way down: on a 390px phone the second
            track resolved to about 105px and the apply card inside it broke to
            one word per line with its button clipped mid-word. `.job-detail-body`
            already collapses at 900px and this page asks the same question, so
            it now uses the same class. */}
        <div className="job-detail-body firm-profile-body">

          {/* Left — details */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '2.5rem' }}>

            {/* First, above the practice areas. Whether an independent guide
                ranks the firm qualifies everything below it, so it belongs
                before the list of what the firm says it does — and it renders
                nothing at all for a firm with no checked entry, so the page
                shape is unchanged for most of the directory. */}
            <RankingBadges firm={firm} variant="full" />

            <section>
              <p className="firm-profile-section-heading">Practice areas</p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
                {firm.practiceAreas.map((area: string) => (
                  <span key={area} className="tag-chip" style={{ fontSize: '0.76rem', padding: '5px 11px' }}>
                    {area}
                  </span>
                ))}
              </div>
            </section>

            {/* Offices.
                Locked, the cities stay and the street addresses go. That split
                is deliberate: knowing a firm has an Ilorin office is what tells
                a reader whether this firm is relevant to them at all, and it is
                the part worth showing for free. The address is the part you
                need only once you have decided to write, which is a fair thing
                to ask for an account in exchange for.

                Keyed by index rather than by city, because a firm can have two
                offices in the same city: OAL has Ikoyi and Apapa, and keying on
                the city name silently dropped one of them. */}
            <section>
              <p className="firm-profile-section-heading">
                {firm.offices.length === 1 ? 'Office' : 'Offices'}
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.9rem' }}>
                {firm.offices.map((office, i) => (
                  <div key={`${office.city}-${i}`} style={{ display: 'flex', gap: '0.7rem', alignItems: 'flex-start' }}>
                    <span style={{ color: 'var(--ink-muted)', marginTop: '3px', flexShrink: 0 }}><MapPinIcon /></span>
                    <div>
                      <p className="firm-office-city">{office.city}</p>
                      {locked ? (
                        <p className="firm-office-address firm-office-address-hidden">
                          Address available to members
                        </p>
                      ) : (
                        <p className="firm-office-address">{office.address}</p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </section>

          </div>

          {/* Right — contact card.
              Was two full-width uppercase blocks of equal weight, one solid
              black and one outlined, stacked under a 3px black rule. Three
              competing heavy elements for what is really one action. The
              application is the action; the website is a reference and now
              reads as a link. */}
          <div className="job-apply-wrap">
            {/* Same carton card the job page uses for its apply panel. The flat
                white box this replaced read as a form field rather than as the
                one thing the page is asking you to do, and it was the only
                surface in the product answering "how do I apply" in its own
                visual language. */}
            <div className="apply-card">
              {locked ? (
                /* The prompt, and the only place on the page that asks for
                 * anything. It sits in the apply card rather than over the
                 * whole page on purpose: an overlay that greys out a profile
                 * teaches a reader that the site is a toll gate, while a card
                 * in the one slot they were heading for reads as the site
                 * telling them where the thing they want is. */
                <>
                  <p className="grotesk-bold apply-card-title">Where to send it</p>
                  <p className="grotesk-regular apply-card-note" style={{ marginTop: 0 }}>
                    {firm.shortName} takes speculative applications, and this is where the
                    application address and the street address for each office live. Members
                    can see both.
                  </p>
                  <Link href={`/auth/signup?redirect=/firms/${firm.slug}`} className="apply-card-cta grotesk-bold" style={{ marginTop: '1.1rem' }}>
                    Create a free account
                  </Link>
                  <p className="grotesk-regular apply-card-note">
                    Already have one?{' '}
                    <Link href={`/auth/login?redirect=/firms/${firm.slug}`} className="apply-card-mail">
                      Sign in
                    </Link>
                    . It takes a minute and the whole directory opens up, not just this firm.
                  </p>
                </>
              ) : (
              <>
              <p className="grotesk-bold apply-card-title">Apply directly</p>

              {firm.email && (
                <>
                  {/* The speculative letter is the main route for a Nigerian law
                      student rather than a fallback, so it is filed exactly like
                      an advertised role. No role name, because there is not one
                      to record. */}
                  <TrackOnApply
                    href={'mailto:' + firm.email}
                    kind="email"
                    label="Send your application"
                    target={{
                      firm: firm.name,
                      role: 'Speculative application',
                      location: firm.offices[0]?.city,
                    }}
                  />
                  <p className="grotesk-regular apply-card-note">
                    Nigerian firms take speculative applications year round. Send your CV and a
                    short cover letter to{' '}
                    <a href={'mailto:' + firm.email} className="apply-card-mail">{firm.email}</a>.
                  </p>
                </>
              )}
              </>
              )}

              {/* Outside the gate. The firm's own website is public knowledge
                  and one search away, so withholding it would cost a reader
                  something real and cost us nothing they could not get. */}
              {firm.website && (
                <a href={firm.website} target="_blank" rel="noopener noreferrer" className="apply-card-link">
                  <GlobeIcon /> Visit website
                </a>
              )}
            </div>
          </div>

        </div>

        {/* Somewhere to go next. Without it the page is a cul-de-sac: read the
            profile, then back-button. Uses only data already in the directory,
            so nothing here is invented. */}
        {related.length > 0 && (
          <div style={{ borderTop: '0.5px solid var(--cream-border)' }}>
            <div style={{ maxWidth: 'min(2200px, 94vw)', margin: '0 auto', padding: '2.5rem 2rem 3.5rem' }}>
              <p className="firm-profile-section-heading">Similar firms</p>
              <div className="firm-related">
                {related.map(f => (
                  <Link key={f.slug} href={`/firms/${f.slug}`} className="firm-related-card">
                    <span className="grotesk-bold firm-related-name">{f.name}</span>
                    <span className="grotesk-regular firm-related-meta">
                      {f.tier} · {f.offices.map(o => o.city).join(' · ')}
                    </span>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        )}
      </main>
      <Footer />
    </>
  )
}

